# Generated by Django 6.0.5 on 2026-05-16 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThoiGianBieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_mon', models.CharField(max_length=200, verbose_name='Tên môn học')),
                ('do_kho', models.CharField(choices=[('cao', 'Khó/Quan trọng (Học sáng)'), ('vua', 'Trung bình (Học chiều)'), ('thap', 'Dễ/Phụ (Học tối)')], default='vua', max_length=10, verbose_name='Độ khó môn học')),
                ('thoi_luong', models.IntegerField(default=2, verbose_name='Số tiếng cần học (giờ)')),
                ('ngay_hoc', models.DateField(blank=True, null=True, verbose_name='Ngày muốn học')),
                ('thoi_gian', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian bắt đầu (Do máy gợi ý)')),
                ('phong_hoc', models.CharField(blank=True, max_length=50, verbose_name='Phòng học/Địa điểm')),
                ('sinh_vien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sinh viên')),
            ],
            options={
                'verbose_name': 'Lịch học',
                'verbose_name_plural': 'Danh sách lịch học',
                'ordering': ['thoi_gian'],
            },
        ),
    ]
